<?php 

 /**
 * Implements hook_theme_registry_alter().
 */
function lodgeweb_preprocess_html(&$variables) {
  // Set module_path
  $module_path = drupal_get_path('module', 'lodgeweb');
  // Add CSS files
  drupal_add_css($module_path . "/_css/frontend/lodgeweb.css", array("group"=>CSS_THEME));
  drupal_add_css($module_path . "/_css/admin/lodgeadmin.css", array("group"=>CSS_THEME));
  drupal_add_css($module_path . "/_css/assets/clear.css", array("group"=>CSS_THEME));
  // Add JS files
  drupal_add_js($module_path . "/_js/lodgeweb.js", array("scope"=>"footer", "group"=>JS_THEME));
  drupal_add_js("https://cdnjs.cloudflare.com/ajax/libs/waypoints/4.0.0/jquery.waypoints.min.js", array("scope"=>"footer","group"=>JS_THEME));
  drupal_add_js("https://use.fontawesome.com/4bc78376e6.js", array("scope"=>"footer", "group"=>JS_THEME));
};

function lodgeweb_theme_registry_alter(&$theme_registry) {
  // Set module_path
  $module_path = drupal_get_path('module', 'lodgeweb');
  $module_path = $module_path . '/_templates';
  // Defined path to the current module.
  $module_path = drupal_get_path('module', 'lodgeweb');
  // Find all .tpl.php files in this module's folder recursively.
  $template_file_objects = drupal_find_theme_templates($theme_registry, '.tpl.php', $module_path);
  // Iterate through all found template file objects.
  foreach ($template_file_objects as $key => $template_file_object) {
    // If the template has not already been overridden by a theme.
    if (!isset($theme_registry[$key]['theme path']) || !preg_match('#/themes/#', $theme_registry[$key]['theme path'])) {
    // Alter the theme path and template elements.
    $theme_registry[$key]['theme path'] = $module_path;
    $theme_registry[$key] = array_merge($theme_registry[$key], $template_file_object);
    $theme_registry[$key]['type'] = 'module';
    };
  };
};